// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pm.Data;

#nullable disable

namespace Pm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103073357_AddSwrSignalTables")]
    partial class AddSwrSignalTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pm.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ActivityLog_UserId");

                    b.HasIndex("Module", "Timestamp")
                        .HasDatabaseName("IX_ActivityLog_Module_Time");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("Pm.Models.CallRecord", b =>
                {
                    b.Property<int>("CallRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CallRecordId"));

                    b.Property<int>("CallCloseReason")
                        .HasColumnType("int");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CallTime")
                        .HasColumnType("time(0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CallRecordId");

                    b.HasIndex("CallCloseReason")
                        .HasDatabaseName("IX_CallRecord_CloseReason");

                    b.HasIndex("CallDate")
                        .HasDatabaseName("IX_CallRecord_Date");

                    b.HasIndex("CallDate", "CallTime")
                        .HasDatabaseName("IX_CallRecord_DateTime");

                    b.ToTable("CallRecords", (string)null);
                });

            modelBuilder.Entity("Pm.Models.CallSummary", b =>
                {
                    b.Property<int>("CallSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CallSummaryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HourGroup")
                        .HasColumnType("int");

                    b.Property<int>("OthersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("OthersPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("date");

                    b.Property<int>("SysBusyCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SysBusyPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TEBusyCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TEBusyPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CallSummaryId");

                    b.HasIndex("SummaryDate", "HourGroup")
                        .IsUnique()
                        .HasDatabaseName("IX_CallSummary_DateHour");

                    b.ToTable("CallSummaries", (string)null);
                });

            modelBuilder.Entity("Pm.Models.FileImportHistory", b =>
                {
                    b.Property<int>("ImportHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImportHistoryId"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ImportHistoryId");

                    b.ToTable("FileImportHistories", (string)null);
                });

            modelBuilder.Entity("Pm.Models.FleetStatistic", b =>
                {
                    b.Property<int>("FleetStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FleetStatisticId"));

                    b.Property<int>("CallCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("date");

                    b.Property<string>("CalledFleet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CallerFleet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FleetStatisticId");

                    b.ToTable("FleetStatistics", (string)null);
                });

            modelBuilder.Entity("Pm.Models.InspeksiTemuanKpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FotoHasilUrls")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoTemuanUrls")
                        .HasColumnType("longtext");

                    b.Property<string>("Inspector")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("KategoriTemuan")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NoFollowUp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PerbaikanDilakukan")
                        .HasColumnType("longtext");

                    b.Property<string>("PicPelaksana")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ruang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime?>("TanggalClosed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TanggalPerbaikan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TanggalSelesaiPerbaikan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TanggalTargetSelesai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalTemuan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Temuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Ruang")
                        .HasDatabaseName("IX_InspeksiTemuanKpc_Ruang");

                    b.HasIndex("TanggalTemuan")
                        .HasDatabaseName("IX_InspeksiTemuanKpc_Tanggal");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_InspeksiTemuanKpc_Deleted_Status");

                    b.ToTable("InspeksiTemuanKpcs", (string)null);
                });

            modelBuilder.Entity("Pm.Models.NEC.NecLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExpectedRslMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ExpectedRslMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FarEndTowerId")
                        .HasColumnType("int");

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NearEndTowerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarEndTowerId");

                    b.HasIndex("LinkName");

                    b.HasIndex("NearEndTowerId");

                    b.ToTable("NecLinks", (string)null);
                });

            modelBuilder.Entity("Pm.Models.NEC.NecRslHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NecLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("RslFarEnd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RslNearEnd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_NecRslHistory_Date");

                    b.HasIndex("NecLinkId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_NecRslHistory_LinkDate");

                    b.ToTable("NecRslHistories", (string)null);
                });

            modelBuilder.Entity("Pm.Models.NEC.Tower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NecTowers", (string)null);
                });

            modelBuilder.Entity("Pm.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_PermissionName");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Pm.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_RoleName");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Pm.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermission_RoleId_PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ExpectedPwrMax")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ExpectedSwrMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(1.5m);

                    b.Property<int>("SwrSiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwrSiteId", "ChannelName")
                        .IsUnique();

                    b.ToTable("SwrChannels", (string)null);
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Fpwr")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SwrChannelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Vswr")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("SwrChannelId", "Date")
                        .IsUnique();

                    b.ToTable("SwrHistories", (string)null);
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SwrSites", (string)null);
                });

            modelBuilder.Entity("Pm.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Pm.Models.ActivityLog", b =>
                {
                    b.HasOne("Pm.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pm.Models.InspeksiTemuanKpc", b =>
                {
                    b.HasOne("Pm.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pm.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pm.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Pm.Models.NEC.NecLink", b =>
                {
                    b.HasOne("Pm.Models.NEC.Tower", "FarEndTower")
                        .WithMany("FarEndLinks")
                        .HasForeignKey("FarEndTowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Models.NEC.Tower", "NearEndTower")
                        .WithMany("NearEndLinks")
                        .HasForeignKey("NearEndTowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FarEndTower");

                    b.Navigation("NearEndTower");
                });

            modelBuilder.Entity("Pm.Models.NEC.NecRslHistory", b =>
                {
                    b.HasOne("Pm.Models.NEC.NecLink", "NecLink")
                        .WithMany("Histories")
                        .HasForeignKey("NecLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NecLink");
                });

            modelBuilder.Entity("Pm.Models.RolePermission", b =>
                {
                    b.HasOne("Pm.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrChannel", b =>
                {
                    b.HasOne("Pm.Models.SWR.SwrSite", "SwrSite")
                        .WithMany("Channels")
                        .HasForeignKey("SwrSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SwrSite");
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrHistory", b =>
                {
                    b.HasOne("Pm.Models.SWR.SwrChannel", "SwrChannel")
                        .WithMany("Histories")
                        .HasForeignKey("SwrChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwrChannel");
                });

            modelBuilder.Entity("Pm.Models.User", b =>
                {
                    b.HasOne("Pm.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pm.Models.NEC.NecLink", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Pm.Models.NEC.Tower", b =>
                {
                    b.Navigation("FarEndLinks");

                    b.Navigation("NearEndLinks");
                });

            modelBuilder.Entity("Pm.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Pm.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrChannel", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Pm.Models.SWR.SwrSite", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Pm.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
