// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Pm.Data;

#nullable disable

namespace Pm.Migrations.KpiMonitoring
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523140000_AddEquipmentTagTypeToHandover")]
    partial class AddEquipmentTagTypeToHandover
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
